services:
  san-francisco-app:
    build: .
    container_name: san-francisco-logistics-app
    ports:
      - "5000:5000"
      - "8080:5000"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - DNS_SERVERS=${DNS_SERVERS}
    restart: always
